name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: 全体を示す一言を書いてください
      placeholder: hogefuga
    validations:
      required: true
  - type: input
    id: reference
    attributes:
      label: Reference
      description: 対応 issue へのリンクを書いてください
      placeholder: https://github.com/onsd/TIL/issues/1
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        incident label の定義
        - AAA / BBB
          - hogehoge
        - AAA / BBB
          - hogehoge
        - AAA / BBB
          - hoge
          - hoge

  - type: input
    id: incident-label
    attributes:
      label: Incident Label
      description: インシデントの分類について書いてください。定義については上記を参照してください。
      placeholder: a - b - c
    validations:
      required: true
  - type: textarea
    id: root-causes
    attributes:
      label: Root Causes
      description: incident, trouble の原因がわかっていれば書いてください。
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
    id: trigger
    attributes:
      label: Trigger
      description: この事象が発生する条件を書いてください
      placeholder: hoge
    validations:
      required: false
  - type: textarea
    id: resolution
    attributes:
      label: Resolution
      description: incident 中に効果があった対応を書く。何もしなければ、「自然復旧」などを書く 
    validations:
      required: true
  - type: textarea
    id: detection
    attributes:
      label: Detection
      description: 検知したError を画面キャプチャや url をあわせて貼ってください
      placeholder: "url: https://example.com"
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: 全体的なタイムラインを記入してください
      placeholder: |
        - 2022/09/14 15:10 インシデント発生
        - 2022/09/14 15:20 インシデント確認
        - 2022/09/14 15:25 revert PR を merge
        - 2022/09/14 15:30 インシデント復旧
  - type: input
    id: incident-caused-at
    attributes:
      label: Incident Caused At
      description: インシデント発生時間を書いてください
      placeholder: "2022/09/14 15:10"
  - type: input
    id: incident-checked-at
    attributes:
      label: Incident Caused At
      description: インシデント確認時間を書いてください
      placeholder: "2022/09/14 15:10"
  - type: input
    id: incident-recovered-at
    attributes:
      label: Incident Caused At
      description: インシデント復旧時間を書いてください
      placeholder: "2022/09/14 15:10"
  - type: textarea
    id: todo
    attributes:
      label: TODO
      description: 今後行う事があれば書いてください
