name: parse issue body
on:
  issues:

jobs:
  place_order:
    if: contains(github.event.issue.labels.*.name , 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug_report.yml
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
           console.log(context)
           const json = JSON.parse('${{ steps.issue-parser.outputs.jsonString }}')
           console.log(json)
