name: preview by comment
on:
  issue_comment:

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

  label:
    if: ${{ github.event.issue.pull_request }}
    #    if: (github.event.issue.pull_request != null) && (github.event.comment.body == '/label A)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const env = {"A":"a", "a":"a", "B": "b", "b": "b"}
            const body = github.event.issue.body.split(' ')
            if (body.length != 2) {
              return
            }
            const label = env[body[1]]
            if (label == null) {
              return
            }
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            })
