name: preview by comment
on:
  issue_comment:
jobs:
  label:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const env = {"A":"a", "a":"a", "B": "b", "b": "b"}
            const body = context.payload.comment.body.split(' ')
            if (body.length != 2) {
              console.log('invalid comment', body)
              return
            }
            const label = env[body[1]]
            if (label == null) {
              console.log("invalid stage. body was", body)
              return
            }
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            })
